version: '3.4'

services:

    catalogdb:
        image: mongo

    basketdb:
        image: redis

    orderdb:
        image: mcr.microsoft.com/mssql/server

    rabbitmq:
        image: rabbitmq:3-management-alpine
    
    catalog.api:
        image: mikolajwalus/microservices/catalogapi
        build:
            context: .
            dockerfile: src/Catalog/Catalog.API/Dockerfile

    basket.api:
        image: mikolajwalus/microservices/basketapi
        build:
            context: .
            dockerfile: src/Basket/Basket.API/Dockerfile


    ordering.api:
        image: mikolajwalus/microservices/orderingapi
        build:
            context: .
            dockerfile: src/Ordering/Ordering.API/Dockerfile


    ocelotapigateway:
        image: mikolajwalus/microservices/ocelotapigateway
        build:
            context: .
            dockerfile: src/ApiGateway/OcelotAPIGateway/Dockerfile

